version: "3"
services:
  confluence:
    container_name: confluence
    image: confluence:6.8.1
    depends_on:
      - confluence-mysql
    volumes:
      - ~/data/confluence/home:/var/atlassian/application-data/confluence
    environment:
      - VIRTUAL_HOST=wiki.bwjf.cn
      - VIRTUAL_PORT=8090
      - CATALINA_CONNECTOR_PROXYNAME=wiki.bwjf.cn
      - CATALINA_CONNECTOR_PROXYPORT=443
      - CATALINA_CONNECTOR_SCHEME=https
    networks:
      - webnet
    links:
      - confluence-mysql
    external_links:
      - ldap
  confluence-mysql:
    container_name: confluence-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: confluence
      MYSQL_USER: confluence
      MYSQL_PASSWORD: confluence
      TZ: Asia/Shanghai
    image: mysql:5.7
    volumes:
      - ~/data/confluence/db:/var/lib/mysql
      # - ~/data/confluence/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --character-set-server=utf8 --collation-server=utf8_bin --transaction-isolation=READ-COMMITTED --innodb-log-file_size=2G --max-allowed-packet=512M
    networks:
      - webnet
networks:
  webnet:
